### ISSUE TITLE
Side-by-side Images

### ISSUE THREAD

**Issue by acartas** [ScanEx/Leaflet.imageTransform#8]
I'm using this plugin to display KML GroundOverlays.
For two side-by-side tiles, some sort of anti-aliasing effect is creating a gridded gap between tiles.

Not sure if this is an issue for the plugin, or just a general thing, but I would love any suggestions.

Looks different on Chrome and Firefox, but similar issue on each. JSFiddle here:
http://jsfiddle.net/TnX96/163/

**Comment by aparshin** [comment]
Unfortunately, it looks like an isuue of browsers' rendering engine more then this plugin. I've checked css transform martices, they are correct.

I have no nice ideas how to solve this issue, only some kind of hacks :) For example, you can extend your boundary by moving all the points a little bit (1%?) in direction opposite to bounds' center. More accurate variant - move them to one pixel (should be updated after each zoom change). Ugly, but should work...

**Comment by aparshin** [comment]
I'm closing this issue, but don't hesitate to reopen it if needed!
