### ISSUE TITLE
setAnchors doesn't accept latLngBounds

### ISSUE THREAD

**Issue by johnwebbcole** [ScanEx/Leaflet.imageTransform#9]
Looks like you can only initialize `imageTransform` or use the setAnchors with an array.  All other Leaflet objects accept both an array and a latLngBouns object.

**Comment by aparshin** [comment]
`anchors` is 4-element array of points (coordinates of 4 image corners). It is arbitrary polygon with four points, not a rectangle (which can be described by `LatLngBounds`).
